AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stub template that allows initializing Cloud Formation stack with Terraform; should be replaced by SAM deploy later

Parameters:
  Namespace:
    Type: String
  CloudWatchLogGroup:
    Type: String
  FunctionRoleArn:
    Type: String

Resources:
  FunctionStub: # Adds a dummy lambda to be replaced by SAM later
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Im a stub! If you get me, something went wrong with SAM deploy', 'statusCode': 200}
